services:
  dolphin-keycloak-db:
    image: postgres:17.4-alpine3.21
    platform: linux/arm64
    container_name: dolphin-keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - dolphin-keycloak-db-data:/var/lib/postgresql/data
    ports:
      - '5300:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${KEYCLOAK_DB_USER} -d ${KEYCLOAK_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - dolphin-keycloak-network

  dolphin-keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    platform: linux/arm64
    container_name: dolphin-keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://dolphin-keycloak-db:5432/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY: edge
      KC_HOSTNAME_ADMIN: localhost
      KC_HOSTNAME_ADMIN_STRICT: false
      KC_HOSTNAME_ADMIN_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_URL: https://localhost
      KC_HOSTNAME_ADMIN_URL: https://localhost
      KC_HOSTNAME_ADMIN_STRICT_BACKCHANNEL: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_FEATURES: preview,admin-fine-grained-authz,admin-api,admin-console,client-policies,client-secret-rotation,impersonation,openid-connect,recovery-codes,scripts,step-up-authentication,user-profile,web-authn
      KC_METRICS_ENABLED: true
      KC_DEBUG: false
      KC_LOG_LEVEL: INFO
    depends_on:
      dolphin-keycloak-db:
        condition: service_healthy
    ports:
      - '5400:8080'
    entrypoint:
      - /opt/keycloak/bin/kc.sh
      - start
      - --health-enabled=true
      - --features=preview,admin-fine-grained-authz,admin-api,admin-console,client-policies,client-secret-rotation,impersonation,openid-connect,recovery-codes,scripts,step-up-authentication,user-profile,web-authn
    networks:
      - dolphin-keycloak-network
      - dolphin-network

  dolphin-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: dolphin-db
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${DOLPHIN_DB_ADMIN_PASSWORD}
      MSSQL_AGENT_ENABLED: true
      MSSQL_TELEMETRY_ENABLED: false
    volumes:
      - dolphin-db-data:/var/opt/mssql
    ports:
      - '5500:1433'
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P ${DOLPHIN_DB_ADMIN_PASSWORD} -C -Q "SELECT @@VERSION" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - dolphin-network

  dolphin-db-initialization:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: dolphin-db-initialization
    depends_on:
      dolphin-db:
        condition: service_healthy
    environment:
      MSSQL_SA_PASSWORD: ${DOLPHIN_DB_ADMIN_PASSWORD}
      SERVER_NAME: dolphin-db
      DATABASE_NAME: ${DOLPHIN_DB}
      DATABASE_USERNAME: ${DOLPHIN_DB_USER}
      DATABASE_PASSWORD: ${DOLPHIN_DB_PASSWORD}
      INIT_SQL_PATH: /usr/src/app/init.sql
    volumes:
      - ./scripts/init.sh:/usr/src/app/init.sh:ro
      - ./scripts/mssql.sql:/usr/src/app/init.sql:ro
    entrypoint: ['/bin/sh', '/usr/src/app/init.sh']
    networks:
      - dolphin-network

  dolphin-db-migrations:
    container_name: dolphin-db-migrations
    platform: linux/arm64
    profiles:
      - migrations
    build:
      context: .
      dockerfile: Dolphin.Migrations/Dockerfile
    depends_on:
      dolphin-db-initialization:
        condition: service_completed_successfully
    environment:
      - server=dolphin-db
      - database=${DOLPHIN_DB}
      - username=${DOLPHIN_DB_USER}
      - password=${DOLPHIN_DB_PASSWORD}
      - migration-name=${MIGRATION_NAME:-}
      - revert=${MIGRATION_REVERT:-false}
    networks:
      - dolphin-network

  dolphin-queries:
    container_name: dolphin-queries
    platform: linux/arm64
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dolphin.Queries.API/Dockerfile
    depends_on:
      dolphin-db:
        condition: service_healthy
      dolphin-db-migrations:
        condition: service_completed_successfully
        required: false
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DolphinDb=Server=dolphin-db;Database=${DOLPHIN_DB};User Id=${DOLPHIN_DB_USER};Password=${DOLPHIN_DB_PASSWORD};TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:80
    ports:
      - '5180:80'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/health', '||', 'exit', '1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - dolphin-network

  dolphin-commands:
    container_name: dolphin-commands
    platform: linux/arm64
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dolphin.Commands.API/Dockerfile
    depends_on:
      dolphin-db:
        condition: service_healthy
      dolphin-db-migrations:
        condition: service_completed_successfully
        required: false
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DolphinDb=Server=dolphin-db;Database=${DOLPHIN_DB};User Id=${DOLPHIN_DB_USER};Password=${DOLPHIN_DB_PASSWORD};TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:80
    ports:
      - '5280:80'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/health', '||', 'exit', '1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - dolphin-network

  dolphin-client:
    container_name: dolphin-client
    platform: linux/arm64
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dolphin.Client/Dockerfile
    networks:
      - dolphin-network

  dolphin-nginx:
    image: nginx:1.25.4-alpine
    platform: linux/arm64
    container_name: dolphin-nginx
    restart: unless-stopped
    depends_on:
      dolphin-queries:
        condition: service_healthy
      dolphin-commands:
        condition: service_healthy
      dolphin-client:
        condition: service_started
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - dolphin-network

volumes:
  dolphin-keycloak-db-data:
    name: dolphin-keycloak-db-data
  dolphin-db-data:
    name: dolphin-db-data

networks:
  dolphin-keycloak-network:
    name: dolphin-keycloak-networ
    driver: bridge
  dolphin-network:
    name: dolphin-network
    driver: bridge
